spring:
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${JDBC_DATABASE_URL}
        hikari:
            minimum-idle: 1
            maximum-pool-size: 5
            pool-name: pocPool
    jpa:
        show-sql: true
        properties:
            hibernate:
                default_schema: salesforce
management:
    context-path: /actuator
    security:
        enabled: false
